# Generated by Django 5.1.7 on 2025-03-22 17:02

import markdownfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_block_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='content_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='content',
            field=markdownfield.models.MarkdownField(blank=True, null=True, rendered_field='content_rendered', verbose_name='Контент (Markdown)'),
        ),
    ]
