# Generated by Django 5.1.7 on 2025-03-22 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_block_content_rendered_alter_block_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='webapp.page', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('text', 'Текстовый блок'), ('slider', 'Слайдер'), ('gallery', 'Галерея')], max_length=20, verbose_name='Тип блока'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='block_images/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Альтернативный текст')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка (для галереи)')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (для галереи)')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание (для галереи)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='webapp.block', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['order'],
            },
        ),
    ]
