# Generated by Django 5.1.7 on 2025-03-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_block_page_alter_block_type_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='title',
            field=models.CharField(default='title', max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
