# Generated by Django 5.1.7 on 2025-03-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_block_options_block_slug_alter_page_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='menu_title',
            field=models.CharField(blank=True, help_text='Необязательное поле. Если указано, будет использоваться в меню вместо основного заголовка.', max_length=255, null=True, verbose_name='Заголовок меню'),
        ),
    ]
