# Generated by Django 5.1.6 on 2025-04-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_sitesettings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('text', 'Текстовый блок'), ('text_right', 'Текст справа'), ('slider', 'Слайдер'), ('gallery', 'Галерея')], max_length=20, verbose_name='Тип блока'),
        ),
    ]
