# Generated by Django 5.1.6 on 2025-04-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
    ]
