# Generated by Django 5.1.6 on 2025-04-12 14:56

import markdownfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_block_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='text_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='text',
            field=markdownfield.models.MarkdownField(blank=True, null=True, rendered_field='text_rendered', verbose_name='Контент (Markdown)'),
        ),
    ]
