# Generated by Django 5.1.6 on 2025-04-12 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_image_text_rendered_alter_image_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='external_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Внешняяы ссылка'),
        ),
        migrations.AddField(
            model_name='block',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.page', verbose_name='Внутренняя ссылка'),
        ),
    ]
