# Generated by Django 5.1.6 on 2025-04-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_block_external_link_block_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='is_text_right',
            field=models.BooleanField(default=False, help_text='Если выбрано, текст будет расположен справа. Иначе — слева.', verbose_name='Текст справа'),
        ),
        migrations.AlterField(
            model_name='block',
            name='external_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='block',
            name='menu_title',
            field=models.CharField(blank=True, help_text='Если указано, будет использоваться в меню вместо основного заголовка.', max_length=255, null=True, verbose_name='Заголовок меню'),
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('text', 'Текстовый блок'), ('lead', 'Лид'), ('slider', 'Слайдер'), ('gallery', 'Галерея')], max_length=20, verbose_name='Тип блока'),
        ),
    ]
