# Generated by Django 5.1.6 on 2025-04-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_block_is_text_right_alter_block_external_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя отправителя.', max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(help_text='Введите номер телефона в международном формате (например, +79991234567).', max_length=20, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, help_text='Введите текст сообщения (опционально).', null=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи.', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('text', 'Текстовый блок'), ('lead', 'Лид'), ('slider', 'Слайдер'), ('gallery', 'Галерея'), ('feedback', 'Форма обратной связи')], max_length=20, verbose_name='Тип блока'),
        ),
    ]
