# Generated by Django 5.1.6 on 2025-04-22 14:00

import django.core.validators
import markdownfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_feedback_alter_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_md',
            field=markdownfield.models.MarkdownField(blank=True, help_text='Введите текст, который будет отображаться в нижней части сайта (футере).', null=True, verbose_name='Текст футера'),
        ),
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название документа.', max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(help_text='Загрузите файл документа.', upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt'])], verbose_name='Файл документа')),
                ('description', models.TextField(blank=True, help_text='Введите описание документа (необязательно).', null=True, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время загрузки документа.', verbose_name='Дата загрузки')),
                ('site_settings', models.ManyToManyField(blank=True, help_text='Выберите настройки сайта, к которым относится этот документ.', related_name='documents', to='webapp.sitesettings', verbose_name='Настройки сайта')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
