# Generated by Django 5.1.6 on 2025-04-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_sitesettings_footer_text_md_alter_block_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='btn_title',
            field=models.CharField(blank=True, help_text='Введите текст для кнопки (необязательно).', max_length=255, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='block',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('text', 'Текстовый блок'), ('lead', 'Лид'), ('slider', 'Главная картинка'), ('gallery', 'Карусель'), ('feedback', 'Форма обратной связи')], max_length=20, verbose_name='Тип блока'),
        ),
    ]
