# Generated by Django 5.1.6 on 2025-04-22 14:40

import markdownfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_block_btn_title_alter_block_order_alter_block_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text_md',
            field=markdownfield.models.MarkdownField(blank=True, help_text='Введите текст, который будет отображаться в нижней части сайта (футере).', null=True, rendered_field='footer_text', verbose_name='Текст футера'),
        ),
    ]
