# Generated by Django 5.1.6 on 2025-04-22 16:36

import django.db.models.deletion
import markdownfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_sitesettings_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='external_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.page', verbose_name='Внутренняя ссылка'),
        ),
        migrations.AlterField(
            model_name='image',
            name='text',
            field=markdownfield.models.MarkdownField(blank=True, null=True, rendered_field='text_rendered', verbose_name='Текст (Markdown)'),
        ),
    ]
