# Generated by Django 5.1.6 on 2025-04-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_remove_image_url_image_external_link_image_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='btn_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст кнопки'),
        ),
    ]
