# Generated by Django 5.1.6 on 2025-04-24 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_image_btn_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок категории.', max_length=255, verbose_name='Заголовок')),
                ('sub_title', models.CharField(blank=True, help_text='Введите подзаголовок категории (необязательно).', max_length=255, null=True, verbose_name='Подзаголовок')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор категории для URL.', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Выберите категорию для страницы (необязательно).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='webapp.category', verbose_name='Категория'),
        ),
    ]
