# Generated by Django 5.1.6 on 2025-04-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_category_page_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['order'], 'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.RemoveConstraint(
            model_name='block',
            name='unique_slug_per_page',
        ),
        migrations.RemoveField(
            model_name='block',
            name='page',
        ),
        migrations.AddField(
            model_name='block',
            name='pages',
            field=models.ManyToManyField(blank=True, help_text='Выберите страницы, к которым относится этот блок.', related_name='blocks', to='webapp.page', verbose_name='Страницы'),
        ),
    ]
