# Generated by Django 5.1.7 on 2025-04-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_alter_block_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='menu_title',
        ),
    ]
