# Generated by Django 5.1.7 on 2025-04-24 18:54

import django.db.models.deletion
import markdownfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_remove_block_menu_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.RemoveField(
            model_name='block',
            name='content_rendered',
        ),
        migrations.RemoveField(
            model_name='block',
            name='order',
        ),
        migrations.RemoveField(
            model_name='block',
            name='pages',
        ),
        migrations.AddField(
            model_name='block',
            name='content_md',
            field=markdownfield.models.MarkdownField(blank=True, null=True, rendered_field='content', verbose_name='Контент (Markdown)'),
        ),
        migrations.AlterField(
            model_name='block',
            name='content',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_pages', to='webapp.block', verbose_name='Блок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_blocks', to='webapp.page', verbose_name='Страница')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('page', 'block')},
            },
        ),
        migrations.AddField(
            model_name='page',
            name='blocks',
            field=models.ManyToManyField(blank=True, help_text='Выберите блоки, которые будут отображаться на этой странице.', related_name='pages', through='webapp.PageBlock', to='webapp.block', verbose_name='Блоки'),
        ),
    ]
