# Generated by Django 5.1.7 on 2025-04-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_alter_block_options_remove_block_content_rendered_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['block_pages__order'], 'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
    ]
