# Generated by Django 5.1.7 on 2025-04-25 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_alter_block_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_categories', to='webapp.block', verbose_name='Блок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_blocks', to='webapp.category', verbose_name='Категория')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('category', 'block')},
            },
        ),
        migrations.AddField(
            model_name='category',
            name='blocks',
            field=models.ManyToManyField(blank=True, help_text='Выберите блоки, которые будут отображаться на этой странице.', related_name='categories', through='webapp.CategoryBlock', to='webapp.block', verbose_name='Блоки'),
        ),
    ]
