# Generated by Django 5.1.7 on 2025-04-25 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webapp', '0029_categoryblock_category_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID элемента')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['category', 'page', 'block']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип элемента')),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_items', to='webapp.sitesettings', verbose_name='Настройки сайта')),
            ],
            options={
                'verbose_name': 'Top Item',
                'verbose_name_plural': 'Top Items',
                'ordering': ['order'],
            },
        ),
    ]
