# Generated by Django 5.1.7 on 2025-04-25 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webapp', '0030_topitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='topitem',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_items', to='webapp.block', verbose_name='Блок'),
        ),
        migrations.AddField(
            model_name='topitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_items', to='webapp.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='topitem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_items', to='webapp.page', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='topitem',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ['category', 'page', 'block']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип элемента'),
        ),
        migrations.AlterField(
            model_name='topitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID элемента'),
        ),
    ]
