# Generated by Django 5.1.7 on 2025-04-25 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_topitem_block_topitem_category_topitem_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topitem',
            name='block',
        ),
        migrations.RemoveField(
            model_name='topitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='topitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='topitem',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='topitem',
            name='page',
        ),
        migrations.AddField(
            model_name='topitem',
            name='category_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_items', to='webapp.categoryblock', verbose_name='Блок на категории'),
        ),
        migrations.AddField(
            model_name='topitem',
            name='page_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_items', to='webapp.pageblock', verbose_name='Блок на странице'),
        ),
        migrations.AddField(
            model_name='topitem',
            name='title',
            field=models.CharField(blank=True, help_text='Необязательный заголовок. Если не указан, используется название страницы или категории.', max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
