# Generated by Django 5.1.7 on 2025-04-26 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webapp', '0033_remove_category_sub_title_category_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topitem',
            name='category_block',
        ),
        migrations.RemoveField(
            model_name='category',
            name='blocks',
        ),
        migrations.AlterUniqueTogether(
            name='pageblock',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='block',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='page',
        ),
        migrations.RemoveField(
            model_name='topitem',
            name='page_block',
        ),
        migrations.RemoveField(
            model_name='page',
            name='blocks',
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title'], 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Уникальный идентификатор для URL.', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='Введите заголовок.', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_homepage',
            field=models.BooleanField(default=False, help_text='Установите этот флаг, если это главная страница.', verbose_name='Главная страница'),
        ),
        migrations.AlterField(
            model_name='page',
            name='logo',
            field=models.ImageField(blank=True, help_text='Загрузите логотип страницы.', null=True, upload_to='site_logos/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='Уникальный идентификатор для URL.', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='Введите заголовок.', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='webapp.block', verbose_name='Блок')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента')),
            ],
            options={
                'verbose_name': 'Связь контента с блоком',
                'verbose_name_plural': 'Связи контента с блоками',
                'ordering': ['order'],
                'unique_together': {('content_type', 'object_id', 'block')},
            },
        ),
        migrations.AddField(
            model_name='topitem',
            name='content_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_items', to='webapp.contentblock', verbose_name='Блок контента'),
        ),
        migrations.DeleteModel(
            name='CategoryBlock',
        ),
        migrations.DeleteModel(
            name='PageBlock',
        ),
    ]
