# Generated by Django 5.1.7 on 2025-04-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_remove_topitem_category_block_remove_category_blocks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['content_blocks__order'], 'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
    ]
