# Generated by Django 5.1.7 on 2025-05-01 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_block_category_alter_block_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat', to='webapp.category', verbose_name='Категория'),
        ),
    ]
