# Generated by Django 5.1.7 on 2025-05-01 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_sitesettings_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='block',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Дата и время создания блока.', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения блока.', verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Дата и время создания блока.', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения блока.', verbose_name='Дата изменения'),
        ),
    ]
