# Generated by Django 5.1.7 on 2025-05-10 17:41

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0040_remove_block_created_at_remove_block_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#FF5733', help_text='Выберите основной цвет для сайта (HEX-значение).', image_field=None, max_length=25, samples=None, verbose_name='Основной цвет'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#33FF57', help_text='Выберите вторичный цвет для сайта (HEX-значение).', image_field=None, max_length=25, samples=None, verbose_name='Вторичный цвет'),
        ),
    ]
