# Generated by Django 5.1.7 on 2025-05-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0041_sitesettings_primary_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='secondary_color',
        ),
    ]
