# Generated by Django 5.1.7 on 2025-05-12 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0042_remove_sitesettings_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='overlay_opacity',
            field=models.FloatField(default=0.5, help_text='Укажите значение от 0 (полностью прозрачный) до 1 (непрозрачный).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Прозрачность оверлея'),
        ),
    ]
