# Generated by Django 5.1.7 on 2025-05-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0043_sitesettings_overlay_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='color_scheme',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная')], default='light', help_text='Выберите цветовую схему для этого блока.', max_length=5, verbose_name='Цветовая схема'),
        ),
    ]
