# Generated by Django 5.1.7 on 2025-05-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0044_contentblock_color_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='color_scheme',
            field=models.CharField(choices=[('dark', 'Тёмная'), ('light', 'Светлая')], default='light', help_text='Выберите цветовую схему для этого блока.', max_length=5, verbose_name='Цветовая схема'),
        ),
    ]
