# Generated by Django 5.1.7 on 2025-05-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0045_alter_contentblock_color_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('text', 'Текстовый блок'), ('lead', 'Лид'), ('slider', 'Главная картинка'), ('gallery', 'Карусель'), ('full_image', 'Большая картинка'), ('feedback', 'Форма обратной связи'), ('category', 'Вывод категории')], max_length=20, verbose_name='Тип блока'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='color_scheme',
            field=models.CharField(choices=[('dark', 'Тёмная'), ('light', 'Светлая')], default='dark', help_text='Выберите цветовую схему для этого блока.', max_length=5, verbose_name='Цветовая схема'),
        ),
    ]
