# Generated by Django 5.1.7 on 2025-05-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0046_alter_block_type_alter_contentblock_color_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='is_text_styled',
            field=models.BooleanField(default=True, help_text='Если выбрано, текст будет отображаться с дополнительным стилем (работает только для текстовых блоков).', verbose_name='Текст стилизован'),
        ),
    ]
