# Generated by Django 5.1.7 on 2025-05-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0048_alter_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allow_in_robots_txt',
            field=models.BooleanField(default=True, help_text='Если установлено, сайт будет доступен для индексации поисковыми роботами.', verbose_name='Разрешено в robots.txt'),
        ),
    ]
