# Generated by Django 5.1.7 on 2025-06-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0049_sitesettings_allow_in_robots_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='menu_title',
            field=models.CharField(blank=True, help_text='Опциональный заголовок, отображаемый в меню навигации.', max_length=255, null=True, verbose_name='Заголовок в меню'),
        ),
    ]
