# Generated by Django 5.1.7 on 2025-06-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0050_contentblock_menu_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Картинка для предварительного просмотра страницы (например, в категории).', null=True, upload_to='page_previews/', verbose_name='Превью-картинка'),
        ),
        migrations.AddField(
            model_name='page',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Картинка для предварительного просмотра страницы (например, в категории).', null=True, upload_to='page_previews/', verbose_name='Превью-картинка'),
        ),
    ]
