# Generated by Django 5.1.7 on 2025-06-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0051_category_preview_image_page_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='preview_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст превью в категории'),
        ),
        migrations.AddField(
            model_name='page',
            name='preview_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст превью в категории'),
        ),
    ]
