# Generated by Django 5.1.7 on 2025-06-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0052_category_preview_text_page_preview_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_api_key',
            field=models.CharField(blank=True, help_text='Введите ключ API для Яндекс сервисов (например, карты).', max_length=255, null=True, verbose_name='Yandex API Key'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_api_point',
            field=models.CharField(blank=True, help_text="Координаты или точка на карте по умолчанию (например, '55.751244,37.618423').", max_length=255, null=True, verbose_name='Yandex API Точка на карте'),
        ),
    ]
