# Generated by Django 5.1.7 on 2025-06-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0053_sitesettings_yandex_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('text', 'Текстовый блок'), ('map', 'Текстовый блок с картой'), ('lead', 'Лид'), ('slider', 'Главная картинка'), ('gallery', 'Карусель'), ('full_image', 'Большая картинка'), ('feedback', 'Форма обратной связи'), ('category', 'Вывод категории'), ('calc', 'Калькулятор')], max_length=20, verbose_name='Тип блока'),
        ),
    ]
