# Generated by Django 5.1.7 on 2025-06-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0054_alter_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='selected_pages',
            field=models.ManyToManyField(blank=True, help_text='Выберите 2–4 страницы, которые будут отображаться как приоритетные для этой категории.', related_name='priority_in_category_blocks', to='webapp.page', verbose_name='Выбранные страницы'),
        ),
    ]
