# Generated by Django 5.1.7 on 2025-06-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0055_block_selected_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='cat_main',
            field=models.CharField(blank=True, help_text='Этот заголовок будет отображаться как основной текст категории на странице.', max_length=255, null=True, verbose_name='Основной заголовок категории'),
        ),
        migrations.AddField(
            model_name='page',
            name='cat_sub',
            field=models.CharField(blank=True, help_text='Этот текст будет отображаться как подзаголовок категории на странице.', max_length=255, null=True, verbose_name='Подзаголовок категории'),
        ),
    ]
