# Generated by Django 5.1.7 on 2025-05-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ключ')),
                ('description', models.TextField(verbose_name='Описание')),
                ('rate_increase', models.DecimalField(decimal_places=2, help_text='Процент изменения ставки при подключении услуги', max_digits=5, verbose_name='Изменение ставки (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
            },
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ключ')),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Минимальное значение')),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Максимальное значение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('data_type', models.CharField(choices=[('decimal', 'Decimal'), ('integer', 'Integer'), ('percent', 'Percent')], default='decimal', max_length=20, verbose_name='Тип данных')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Диапазон',
                'verbose_name_plural': 'Диапазоны',
            },
        ),
        migrations.CreateModel(
            name='CalculatorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость недвижимости')),
                ('initial_payment_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Первоначальный взнос (%)')),
                ('loan_term_years', models.PositiveIntegerField(verbose_name='Срок кредита (лет)')),
                ('use_maternity_capital', models.BooleanField(default=False, verbose_name='Использовать материнский капитал')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('selected_services', models.ManyToManyField(blank=True, to='calc.additionalservice', verbose_name='Выбранные услуги')),
            ],
            options={
                'verbose_name': 'Расчёт калькулятора',
                'verbose_name_plural': 'Расчёты калькулятора',
            },
        ),
    ]
