# Generated by Django 5.1.7 on 2025-05-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Например: 14.5%', max_digits=5, verbose_name='Базовая процентная ставка (%)')),
            ],
            options={
                'verbose_name': 'Базовая ставка',
                'verbose_name_plural': 'Базовые ставки',
            },
        ),
    ]
