# Generated by Django 5.1.7 on 2025-06-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_baserate'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='default_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Значение, используемое по умолчанию, если не указано иное', max_digits=12, null=True, verbose_name='Значение по умолчанию'),
        ),
    ]
