# Generated by Django 5.1.7 on 2025-06-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_range_default_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='range',
            options={'ordering': ['order'], 'verbose_name': 'Диапазон', 'verbose_name_plural': 'Диапазоны'},
        ),
        migrations.AddField(
            model_name='range',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Укажите порядок отображения (если не указан — будет установлен автоматически)', null=True, verbose_name='Порядок'),
        ),
    ]
