# Generated by Django 5.1.7 on 2025-10-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_alter_range_options_range_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='step',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Шаг изменения значения в калькуляторе', max_digits=12, null=True, verbose_name='Шаг'),
        ),
    ]
