# Generated by Django 5.1.7 on 2025-10-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0014_range_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='step',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Шаг изменения значения в калькуляторе', max_digits=12, verbose_name='Шаг'),
        ),
    ]
